/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package views;

import controllers.EmpresaControlador;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import models.Empresa;

/**
 *
 * @author ever_vc
 */
public class GestionEmpresa extends javax.swing.JPanel {
    
    private int _idEmpresaSeleccionada = -1;
    private Principal _frmPrincipal;
    private Validaciones validar = new Validaciones();
    javax.swing.JTextField[] _jtxts;

    /**
     * Creates new form GestionEmpresa
     */
    public GestionEmpresa() {
        initComponents();
        CargarEmpresas();// Carga las empresas en la tabla
        // Diseño de la tabla => Crea un renderer para personalizar el encabezado
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(new java.awt.Color(0,51,51)); // Cambia el color de fondo del encabezado al del diseño principal new java.awt.Color(0,51,51)
        headerRenderer.setForeground(Color.WHITE); // Cambia el color de la fuente del encabezado

        // Asigna el renderer a cada columna del encabezado
        for (int i = 0; i < jtblEmpresas.getColumnModel().getColumnCount(); i++) {
            jtblEmpresas.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        
        // Cambia el fondo de la tabla
        jtblEmpresas.setBackground(new java.awt.Color(242,247,251)); // Fondo de la tabla (celdas)
        // Cambia el fondo del área vacía de la tabla
        jtblEmpresas.setFillsViewportHeight(true);
        jtblEmpresas.getParent().setBackground(new java.awt.Color(242,247,251)); // Fondo del viewport
        _jtxts = new javax.swing.JTextField[] {jtxtNombre, jtxtPropietario, jtxtDireccion, jtxtEmail};
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEmpresas = new javax.swing.JTable();
        jbtnCatalogoCuentas = new javax.swing.JButton();
        jbtnGuardar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnLimpiar = new javax.swing.JButton();
        jpnlForm = new javax.swing.JPanel();
        jlblDireccion = new javax.swing.JLabel();
        jlblEmail = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtPropietario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtEmail = new javax.swing.JTextField();
        jlblNombreEmpresa = new javax.swing.JLabel();
        jlblPropietario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 247, 251));
        setPreferredSize(new java.awt.Dimension(1051, 835));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jlblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlblTitulo.setForeground(new java.awt.Color(0, 51, 51));
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setText("GESTION DE EMPRESAS");

        jtblEmpresas.setBackground(new java.awt.Color(242, 247, 251));
        jtblEmpresas.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jtblEmpresas.setForeground(new java.awt.Color(0, 51, 51));
        jtblEmpresas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "DIRECCION", "PROPIETARIO", "EMAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblEmpresas.setGridColor(new java.awt.Color(0, 51, 51));
        jtblEmpresas.setRowHeight(25);
        jtblEmpresas.setSelectionBackground(new java.awt.Color(26, 173, 220));
        jtblEmpresas.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jtblEmpresas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblEmpresas.setShowGrid(true);
        jtblEmpresas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblEmpresasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblEmpresas);
        if (jtblEmpresas.getColumnModel().getColumnCount() > 0) {
            jtblEmpresas.getColumnModel().getColumn(0).setResizable(false);
            jtblEmpresas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jtblEmpresas.getColumnModel().getColumn(1).setResizable(false);
            jtblEmpresas.getColumnModel().getColumn(1).setPreferredWidth(250);
            jtblEmpresas.getColumnModel().getColumn(2).setResizable(false);
            jtblEmpresas.getColumnModel().getColumn(2).setPreferredWidth(250);
            jtblEmpresas.getColumnModel().getColumn(3).setResizable(false);
            jtblEmpresas.getColumnModel().getColumn(3).setPreferredWidth(250);
            jtblEmpresas.getColumnModel().getColumn(4).setResizable(false);
            jtblEmpresas.getColumnModel().getColumn(4).setPreferredWidth(250);
        }

        jbtnCatalogoCuentas.setBackground(new java.awt.Color(0, 51, 51));
        jbtnCatalogoCuentas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCatalogoCuentas.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCatalogoCuentas.setText("ABRIR CATALOGO DE CUENTAS");
        jbtnCatalogoCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCatalogoCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCatalogoCuentasActionPerformed(evt);
            }
        });

        jbtnGuardar.setBackground(new java.awt.Color(0, 51, 0));
        jbtnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnGuardar.setText("GUARDAR");
        jbtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarActionPerformed(evt);
            }
        });

        jbtnEliminar.setBackground(new java.awt.Color(51, 0, 0));
        jbtnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnEliminar.setText("ELIMINAR");
        jbtnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarActionPerformed(evt);
            }
        });

        jbtnLimpiar.setBackground(new java.awt.Color(0, 51, 51));
        jbtnLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        jbtnLimpiar.setText("LIMPIAR CAMPOS");
        jbtnLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLimpiarActionPerformed(evt);
            }
        });

        jpnlForm.setBackground(new java.awt.Color(242, 247, 251));
        jpnlForm.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jlblDireccion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblDireccion.setForeground(new java.awt.Color(0, 51, 51));
        jlblDireccion.setText("Dirección:");

        jlblEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblEmail.setForeground(new java.awt.Color(0, 51, 51));
        jlblEmail.setText("Corrreo electrónico:");

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("*");

        jtxtNombre.setBackground(new java.awt.Color(242, 247, 251));
        jtxtNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtNombre.setForeground(new java.awt.Color(204, 204, 204));
        jtxtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtNombre.setText("Ingrese el nombre...");
        jtxtNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jtxtNombre.setCaretColor(new java.awt.Color(0, 51, 51));
        jtxtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtNombreFocusLost(evt);
            }
        });
        jtxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNombreKeyTyped(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("*");

        jtxtPropietario.setBackground(new java.awt.Color(242, 247, 251));
        jtxtPropietario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtPropietario.setForeground(new java.awt.Color(204, 204, 204));
        jtxtPropietario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtPropietario.setText("Ingrese el nombre del propietario...");
        jtxtPropietario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jtxtPropietario.setCaretColor(new java.awt.Color(0, 51, 51));
        jtxtPropietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPropietarioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPropietarioFocusLost(evt);
            }
        });
        jtxtPropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtPropietarioKeyTyped(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("*");

        jtxtDireccion.setBackground(new java.awt.Color(242, 247, 251));
        jtxtDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDireccion.setForeground(new java.awt.Color(204, 204, 204));
        jtxtDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtDireccion.setText("Ingrese la dirección...");
        jtxtDireccion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jtxtDireccion.setCaretColor(new java.awt.Color(0, 51, 51));
        jtxtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtDireccionFocusLost(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("*");

        jtxtEmail.setBackground(new java.awt.Color(242, 247, 251));
        jtxtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtEmail.setForeground(new java.awt.Color(204, 204, 204));
        jtxtEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtEmail.setText("Ingrese el correo electrónico...");
        jtxtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jtxtEmail.setCaretColor(new java.awt.Color(0, 51, 51));
        jtxtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtEmailFocusLost(evt);
            }
        });
        jtxtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtEmailKeyTyped(evt);
            }
        });

        jlblNombreEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblNombreEmpresa.setForeground(new java.awt.Color(0, 51, 51));
        jlblNombreEmpresa.setText("Nombre de la empresa:");

        jlblPropietario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblPropietario.setForeground(new java.awt.Color(0, 51, 51));
        jlblPropietario.setText("Nombre del propietario:");

        javax.swing.GroupLayout jpnlFormLayout = new javax.swing.GroupLayout(jpnlForm);
        jpnlForm.setLayout(jpnlFormLayout);
        jpnlFormLayout.setHorizontalGroup(
            jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jtxtDireccion)
                        .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlFormLayout.createSequentialGroup()
                        .addComponent(jlblNombreEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlFormLayout.createSequentialGroup()
                        .addComponent(jlblDireccion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89)
                .addGroup(jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtPropietario)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlFormLayout.createSequentialGroup()
                        .addComponent(jlblPropietario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnlFormLayout.createSequentialGroup()
                        .addComponent(jlblEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlFormLayout.setVerticalGroup(
            jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblNombreEmpresa)
                    .addComponent(jLabel1)
                    .addComponent(jlblPropietario)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblDireccion)
                    .addComponent(jLabel4)
                    .addComponent(jlblEmail)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnCatalogoCuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(289, 289, 289))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 128, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
            .addGroup(layout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jlblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 914, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnCatalogoCuentas)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarActionPerformed
        // TODO add your handling code here:
        String nombreEmpresa = jtxtNombre.getText();
        String propietario = jtxtPropietario.getText();
        String direccion = jtxtDireccion.getText();
        String email = jtxtEmail.getText();
        // Valida que los campos obligatorios contengan la información
        if (!ValidarCamposObligatorios(nombreEmpresa, propietario, direccion, email)) {
            return;
        }
        
        if (!validar.ValidarEmail(email)) { // Valida que el email contenga el formato
            validar.JtxtErrorColor(jtxtEmail);
            JOptionPane.showMessageDialog(null, "EL [EMAIL] QUE HA INGRESADO NO ES VALIDO, ASEGURESE DE HABERLO ESCRITO CORRECTAMENTE.","ERROR:", JOptionPane.ERROR_MESSAGE);
            return; // Sino coincide, entonces retorna
        }
        
        if (_idEmpresaSeleccionada != -1) { // Actualizar información de empresa
            Empresa empresaActualizada = EmpresaControlador.Instancia().GetEmpresaPorId(_idEmpresaSeleccionada);
            
            // Almacena la información actualizada de la empresa
            empresaActualizada.setNombre(nombreEmpresa);
            empresaActualizada.setDireccion(direccion);
            empresaActualizada.setEmail(email);
            
            EmpresaControlador.Instancia().ActualizarEmpresa(empresaActualizada);
            JOptionPane.showMessageDialog(null, "LA EMPRESA HA SIDO ACTUALIZADA EN LA BASE DE DATOS EXITOSAMENTE.","TAREA REALIZADA CON EXITO:", JOptionPane.INFORMATION_MESSAGE);
        } else { // Crear nueva empresa
            Empresa nuevaEmpresa = new Empresa();
            
            // Almacena la información actualizada de la empresa
            nuevaEmpresa.setNombre(nombreEmpresa);
            nuevaEmpresa.setDireccion(direccion);
            nuevaEmpresa.setEmail(email);
            
            EmpresaControlador.Instancia().CrearEmpresa(nuevaEmpresa);
            JOptionPane.showMessageDialog(null, "LA EMPRESA HA SIDO REGISTRADA EN LA BASE DE DATOS EXITOSAMENTE.","TAREA REALIZADA CON EXITO:", JOptionPane.INFORMATION_MESSAGE);
        }
        LimpiarTodo();
        CargarEmpresas();
    }//GEN-LAST:event_jbtnGuardarActionPerformed

    private void jbtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarActionPerformed
        // TODO add your handling code here:
        if (_idEmpresaSeleccionada != -1) {
            Empresa empresaAEliminar = EmpresaControlador.Instancia().GetEmpresaPorId(_idEmpresaSeleccionada);
            int response = JOptionPane.showConfirmDialog(
                GestionEmpresa.this,
                "¿Estás seguro de que deseas eliminar la empresa " + empresaAEliminar.getNombre() + " de la base de datos? Este proceso no se puede revertir.",
                "ATENCIÓN:",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
            );

            if (response == JOptionPane.YES_OPTION) {
                EmpresaControlador.Instancia().EliminarEmpresa(_idEmpresaSeleccionada);
                JOptionPane.showMessageDialog(null, "LA EMPRESA HA SIDO ELIMINADA DE LA BASE DE DATOS EXITOSAMENTE.","TAREA REALIZADA CON EXITO:", JOptionPane.INFORMATION_MESSAGE);
                CargarEmpresas();// Recarga la tabla para actualizarla
                LimpiarTodo();// Limpia todos los campos
            }
        } else {
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE DESDE LA TABLA LA EMPRESA QUE DESEA ELIMINAR.","ERROR:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnEliminarActionPerformed

    private void jbtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLimpiarActionPerformed
        // TODO add your handling code here:
        LimpiarTodo();
    }//GEN-LAST:event_jbtnLimpiarActionPerformed

    private void jtblEmpresasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEmpresasMouseClicked
        // TODO add your handling code here:
        int selectedRow = jtblEmpresas.getSelectedRow();
    
        // Verifica que una fila válida esté seleccionada (Es decir que no haya dado click en un espacio vacío)
        if (selectedRow >= 0) {
            _idEmpresaSeleccionada = Integer.parseInt(jtblEmpresas.getValueAt(selectedRow, 0).toString());
            validar.JtxtColorInicialTexto(_jtxts, new java.awt.Color(0,51,51));
            JtxtFinFoco();
            CargarDatosDeEmpresaSeleccionada();
        }
        //_idEmpresaSeleccionada = Integer.parseInt(jtblEmpresas.getValueAt(jtblEmpresas.getSelectedRow(), 0).toString());
        //CargarDatosDeEmpresaSeleccionada();
    }//GEN-LAST:event_jtblEmpresasMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if (_idEmpresaSeleccionada != -1) {
            LimpiarTodo(); // Si se ha seleccionado un registro de la tabla, deselecciona el registro y limpia todo
        }
    }//GEN-LAST:event_formMouseClicked

    private void jbtnCatalogoCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCatalogoCuentasActionPerformed
        // TODO add your handling code here:
        if (_idEmpresaSeleccionada != -1) {
            _frmPrincipal.AbrirSubPanel(new CatalogoCuentas(_idEmpresaSeleccionada));
        } else {
            JOptionPane.showMessageDialog(null, "POR FAVOR SELECCIONE DESDE LA TABLA A LA EMPRESA QUE DESEA ADMINISTRARLE EL CATALOGO DE CUENTAS.","ERROR:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnCatalogoCuentasActionPerformed

    private void jtxtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNombreKeyTyped
        // TODO add your handling code here:
        validar.ValidarLetrasYEspacios(evt);
    }//GEN-LAST:event_jtxtNombreKeyTyped

    private void jtxtPropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPropietarioKeyTyped
        // TODO add your handling code here:
        validar.ValidarLetrasYEspacios(evt);
    }//GEN-LAST:event_jtxtPropietarioKeyTyped

    private void jtxtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtEmailKeyTyped
        // TODO add your handling code here:
        validar.ValidarTodoMenosEspacios(evt);
    }//GEN-LAST:event_jtxtEmailKeyTyped

    private void jtxtNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombreFocusGained
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtNombre, true);
        validar.JtxtEfectoPlaceHolder(jtxtNombre, "Ingrese el nombre...", true);
    }//GEN-LAST:event_jtxtNombreFocusGained

    private void jtxtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtNombreFocusLost
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtNombre, false);
        validar.JtxtEfectoPlaceHolder(jtxtNombre, "Ingrese el nombre...", false);
    }//GEN-LAST:event_jtxtNombreFocusLost

    private void jtxtPropietarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPropietarioFocusGained
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtPropietario, true);
        validar.JtxtEfectoPlaceHolder(jtxtPropietario, "Ingrese el nombre del propietario...", true);
    }//GEN-LAST:event_jtxtPropietarioFocusGained

    private void jtxtPropietarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPropietarioFocusLost
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtPropietario, false);
        validar.JtxtEfectoPlaceHolder(jtxtPropietario, "Ingrese el nombre del propietario...", false);
    }//GEN-LAST:event_jtxtPropietarioFocusLost

    private void jtxtDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDireccionFocusGained
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtDireccion, true);
        validar.JtxtEfectoPlaceHolder(jtxtDireccion, "Ingrese la dirección...", true);
    }//GEN-LAST:event_jtxtDireccionFocusGained

    private void jtxtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtDireccionFocusLost
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtDireccion, false);
        validar.JtxtEfectoPlaceHolder(jtxtDireccion, "Ingrese la dirección...", false);
    }//GEN-LAST:event_jtxtDireccionFocusLost

    private void jtxtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEmailFocusGained
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtEmail, true);
        validar.JtxtEfectoPlaceHolder(jtxtEmail, "Ingrese el correo electrónico...", true);
    }//GEN-LAST:event_jtxtEmailFocusGained

    private void jtxtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEmailFocusLost
        // TODO add your handling code here:
        validar.JtxtFocoCambiarColor(jtxtEmail, false);
        validar.JtxtEfectoPlaceHolder(jtxtEmail, "Ingrese el correo electrónico...", false);
    }//GEN-LAST:event_jtxtEmailFocusLost

    public void SetFormularioPrincipal(Principal frmPrincipal) {
        this._frmPrincipal = frmPrincipal;
    }
    
    private boolean ValidarCamposObligatorios(String nombre, String propietario, String direccion, String email) {
        boolean sonValidos = true;
        int cantidadCamposInvalidos = 0;
        String camposNoValidos = "";
        if ("Ingrese el nombre...".equals(nombre)) {
            validar.JtxtErrorColor(jtxtNombre);
            cantidadCamposInvalidos ++;
            camposNoValidos += "\n~ NOMBRE DE LA EMPRESA";
            
            //JOptionPane.showMessageDialog(null, "PARECE QUE HA OLVIDADO LLENAR EL CAMPO DE [NOMBRE], POR FAVOR ASEGURESE DE LLENAR CORRECTAMENTE TODOS LOS CAMPOS QUE CONTIENEN UN [*].","ERROR:", JOptionPane.ERROR_MESSAGE);
            sonValidos = false;
        }
        if ("Ingrese el nombre del propietario...".equals(propietario)) {
            validar.JtxtErrorColor(jtxtPropietario);
            cantidadCamposInvalidos ++;
            camposNoValidos += "\n~ NOMBRE DEL PROPIETARIO";
            //JOptionPane.showMessageDialog(null, "PARECE QUE HA OLVIDADO LLENAR EL CAMPO DE [PROPIETARIO], POR FAVOR ASEGURESE DE LLENAR CORRECTAMENTE TODOS LOS CAMPOS QUE CONTIENEN UN [*].","ERROR:", JOptionPane.ERROR_MESSAGE);
            sonValidos = false;
        }
        if ("Ingrese la dirección...".equals(direccion)) {
            validar.JtxtErrorColor(jtxtDireccion);
            cantidadCamposInvalidos ++;
            camposNoValidos += "\n~ DIRECCIÓN";
            //JOptionPane.showMessageDialog(null, "PARECE QUE HA OLVIDADO SELECCIONAR EL CAMPO DE [DIRECCION], POR FAVOR ASEGURESE DE LLENAR CORRECTAMENTE TODOS LOS CAMPOS QUE CONTIENEN UN [*].","ERROR:", JOptionPane.ERROR_MESSAGE);
            sonValidos = false;
        }
        if ("Ingrese el correo electrónico...".equals(email)) {
            validar.JtxtErrorColor(jtxtEmail);
            cantidadCamposInvalidos ++;
            camposNoValidos += "\n~ CORREO";
            sonValidos = false;
        }
        
        if (!sonValidos) {
            if (cantidadCamposInvalidos > 1) {
                JOptionPane.showMessageDialog(null, "PARECE QUE HA OLVIDADO LLENAR LOS CAMPOS: " + camposNoValidos + "\nPOR FAVOR ASEGURESE DE LLENAR CORRECTAMENTE TODOS LOS CAMPOS QUE CONTIENEN UN [*].","ERROR:", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "PARECE QUE HA OLVIDADO LLENAR EL CAMPO DE: " + camposNoValidos + "\nPOR FAVOR ASEGURESE DE LLENAR CORRECTAMENTE TODOS LOS CAMPOS QUE CONTIENEN UN [*].","ERROR:", JOptionPane.ERROR_MESSAGE);
            }
        }   
        
        return sonValidos; // Retorna verdadero únicamente cuando todos los campos tienen datos
    }
    
    private void CargarEmpresas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo = (DefaultTableModel)jtblEmpresas.getModel();
        modelo.setRowCount(0);//Limpia todas los registros de la tabla (indicando que no quiere ninguna fila)
        List<Empresa> lstEmpresas = EmpresaControlador.Instancia().GetListaEmpresas();
        
        for (Empresa empresa : lstEmpresas) {
            modelo.addRow(new Object[]{empresa.getId(), empresa.getNombre(), empresa.getDireccion(), "-- Sin definir --", empresa.getEmail()});
        }
    }
    
    private void CargarDatosDeEmpresaSeleccionada() {
        if (_idEmpresaSeleccionada != -1) {
            Empresa empresaSeleccionada = EmpresaControlador.Instancia().GetEmpresaPorId(_idEmpresaSeleccionada);
            jtxtNombre.setText(empresaSeleccionada.getNombre());
            jtxtPropietario.setText("-- Sin definir --");
            jtxtDireccion.setText(empresaSeleccionada.getDireccion());
            jtxtEmail.setText(empresaSeleccionada.getEmail());
        }
    }
    
    private void LimpiarTodo() {
        jtxtNombre.setText("Ingrese el nombre...");
        jtxtPropietario.setText("Ingrese el nombre del propietario...");
        jtxtDireccion.setText("Ingrese la dirección...");
        jtxtEmail.setText("Ingrese el correo electrónico...");
        _idEmpresaSeleccionada = -1;
        jtblEmpresas.clearSelection();
        JtxtFinFoco();
        validar.JtxtColorInicialTexto(_jtxts, new java.awt.Color(204, 204, 204));
    }
    
    private void JtxtFinFoco() {
        validar.JtxtColorInicial(jtxtNombre);
        validar.JtxtColorInicial(jtxtPropietario);
        validar.JtxtColorInicial(jtxtDireccion);
        validar.JtxtColorInicial(jtxtEmail);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnCatalogoCuentas;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnGuardar;
    private javax.swing.JButton jbtnLimpiar;
    private javax.swing.JLabel jlblDireccion;
    private javax.swing.JLabel jlblEmail;
    private javax.swing.JLabel jlblNombreEmpresa;
    private javax.swing.JLabel jlblPropietario;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JPanel jpnlForm;
    private javax.swing.JTable jtblEmpresas;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtEmail;
    private javax.swing.JTextField jtxtNombre;
    private javax.swing.JTextField jtxtPropietario;
    // End of variables declaration//GEN-END:variables
}
