/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.SessionLogControlador;
import controllers.UsuarioControlador;
import java.util.Date;
import javax.swing.JOptionPane;
import models.SessionLog;
import models.Usuario;
import support.UsuarioCache;

/**
 *
 * @author ever_vc
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jbtnLogin = new javax.swing.JButton();
        jtxtPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlblTitulo.setText("LOGIN");

        jtxtUsername.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario:"));

        jbtnLogin.setText("INICIAR SESION");
        jbtnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jtxtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña:"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jlblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtUsername)
                            .addComponent(jbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(jtxtPassword))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlblTitulo)
                .addGap(59, 59, 59)
                .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        //Valida que los campos no estén vacíos
        if (!"".equals(jtxtUsername.getText())) {
            if (!"".equals(jtxtPassword.getText())) {
                
                String username = jtxtUsername.getText();
                String password = jtxtPassword.getText();
                
                /*if ("create".equals(username) && "admin".equals(password)) {
                    UsuarioControlador.Instancia().CrearAdministradorInicial();
                }*/
                
                Usuario usuarioLogin = new Usuario();
                usuarioLogin.setUsername(username);
                usuarioLogin.setPassword(password);
                
                int idUsuarioLogin = UsuarioControlador.Instancia().ValidarLogin(usuarioLogin);
                
                if (idUsuarioLogin == -1) {
                    // Caso de usuario no encontrado
                    JOptionPane.showMessageDialog(null, "EL USUARIO QUE HA INGRESADO NO EXISTE EN LA BASE DE DATOS, POR FAVOR ASEGURESE DE HABER INGRESADO CORRECTAMENTE LA INFORMACION.","CREDENCIALES INCORRECTAS:", JOptionPane.ERROR_MESSAGE);
                } else if (idUsuarioLogin == -2) {
                    // Caso de contraseña incorrecta
                    JOptionPane.showMessageDialog(null, "LA CONTRASEÑA QUE HA INGRESADO NO COINCIDE CON EL NOMBRE DE USUARIO, POR FAVOR ASEGURESE DE HABER INGRESADO CORRECTAMENTE LA INFORMACION.","CREDENCIALES INCORRECTAS:", JOptionPane.ERROR_MESSAGE);
                } else {
                    usuarioLogin = UsuarioControlador.Instancia().GetUsuarioPorId(idUsuarioLogin);
                    SessionLog sesionDeUsuario = SessionLogControlador.instancia().ObtenerSesionPorUsuario(idUsuarioLogin);
                    if (sesionDeUsuario == null) {
                        sesionDeUsuario = new SessionLog();
                        sesionDeUsuario.setIdUsuarioFk(usuarioLogin);
                        sesionDeUsuario.setLoginTimestamp(new Date());
                        SessionLogControlador.instancia().CreararInicioDeSesion(sesionDeUsuario);
                    } else {
                        System.out.println("Sesion encontrada, ultima conexión a las " + sesionDeUsuario.getLoginTimestamp());
                        sesionDeUsuario.setLoginTimestamp(new Date());
                        System.out.println("Nuevo inicio de sesión a las " + sesionDeUsuario.getLoginTimestamp());
                        SessionLogControlador.instancia().GuardarInicioDeSesion(sesionDeUsuario);
                    }
                    
                    UsuarioCache.Id = idUsuarioLogin;
                    UsuarioCache.Nombres = usuarioLogin.getNombres();
                    UsuarioCache.Apellidos = usuarioLogin.getApellidos();
                    UsuarioCache.Sexo = usuarioLogin.getSexo();
                    UsuarioCache.FechaNacimiento = usuarioLogin.getFechaNacimiento();
                    UsuarioCache.Direccion = usuarioLogin.getDireccion();
                    UsuarioCache.Email = usuarioLogin.getEmail();
                    UsuarioCache.Username = usuarioLogin.getUsername();
                    UsuarioCache.RolUsuario = usuarioLogin.getIdRolFk().getNombre();
                    
                    Principal frmPrincipal = new Principal();
                    frmPrincipal.CargarUsuario(idUsuarioLogin);
                    this.dispose();
                    frmPrincipal.show();

                    //JOptionPane.showMessageDialog(null, "BIENVENIDO, EL ID DE USUARIO ES: " + idUsuarioLogin, "LOGIN EXITOSO:", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "DEBE INGRESAR SU CONTRASEÑA EN EL FORMULARIO.","ERROR:", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "DEBE INGRESAR SU NOMBRE DE USUARIO EN EL FORMULARIO.","ERROR:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables
}
