/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import controllers.SessionLogControlador;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import models.Cuenta;
import models.SessionLog;
import support.UsuarioCache;

/**
 *
 * @author ever_vc
 */
public class Principal extends javax.swing.JFrame {
    
    private static int _visible = -1;
    private Login _frmLogin;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Inicio panel = new Inicio();
        panel.setSize(jpnlContenedor.getWidth(), jpnlContenedor.getHeight());
        panel.setLocation(0, 0);
        jpnlContenedor.removeAll();
        jpnlContenedor.add(panel, BorderLayout.CENTER);
        jpnlContenedor.revalidate();
        jpnlContenedor.repaint();
        
        jlblNombreUsuario.setText(UsuarioCache.GetNombreApellidoUsuario());
        String url = "src/assets/avatarUserM.png";
        if (UsuarioCache.Sexo.equals("Femenino")) {
            url = "src/assets/avatarUserW.png";
        }
        
        SetImagLabel(jimgUsuario, url);
        
        // Añade WindowListener para manejar el evento de cierre (Consultar si está seguro de cerrar la app)
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                    Principal.this,
                    "Actualmente tiene una sesión iniciada ¿Estás seguro de que deseas salir y cerrar por completo la sesión?",
                    "ATENCIÓN:",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE
                );

                if (response == JOptionPane.YES_OPTION) {
                    // Obtiene la sesion abierta actualmente a través del id del usuario logueado
                    SessionLog sesionDeUsuario = SessionLogControlador.instancia().ObtenerSesionPorUsuario(UsuarioCache.Id);
                    sesionDeUsuario.setLogoutTimestamp(new Date());// Almacena la hora de cierre de sesión por parte del usuario
                    SessionLogControlador.instancia().GuardarCierreDeSesion(sesionDeUsuario);// Guarda la información
                    System.out.println("Cierre de sesión registrado a las " + sesionDeUsuario.getLogoutTimestamp());
                    System.exit(0);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlMenu = new javax.swing.JPanel();
        jbtnInicio = new javax.swing.JButton();
        jbtnUsuarios = new javax.swing.JButton();
        jlblNombreUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jbtnEditarPerfil = new javax.swing.JButton();
        jimgUsuario = new javax.swing.JLabel();
        jbtnEmpresas = new javax.swing.JButton();
        jbtnAsientos = new javax.swing.JButton();
        jbtnLibroDiario = new javax.swing.JButton();
        jbtnLibroMayor = new javax.swing.JButton();
        jbtnCerrarSesion = new javax.swing.JButton();
        jpnlContenedor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jpnlMenu.setBackground(new java.awt.Color(24, 30, 54));

        jbtnInicio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnInicio.setText("INICIO");
        jbtnInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnInicioActionPerformed(evt);
            }
        });

        jbtnUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnUsuarios.setText("GESTION DE USUARIOS");
        jbtnUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUsuariosActionPerformed(evt);
            }
        });

        jlblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlblNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlblNombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblNombreUsuario.setText("Nombre Usuario");

        jbtnEditarPerfil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnEditarPerfil.setText("Editar perfil");

        jimgUsuario.setBackground(new java.awt.Color(51, 51, 255));
        jimgUsuario.setOpaque(true);

        jbtnEmpresas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnEmpresas.setText("GESTION DE EMPRESAS");
        jbtnEmpresas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEmpresasActionPerformed(evt);
            }
        });

        jbtnAsientos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnAsientos.setText("ASIENTO CONTABLE");
        jbtnAsientos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnAsientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAsientosActionPerformed(evt);
            }
        });

        jbtnLibroDiario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnLibroDiario.setText("LIBRO DIARIO");
        jbtnLibroDiario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLibroDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLibroDiarioActionPerformed(evt);
            }
        });

        jbtnLibroMayor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnLibroMayor.setText("LIBRO MAYOR");
        jbtnLibroMayor.setToolTipText("");
        jbtnLibroMayor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnLibroMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLibroMayorActionPerformed(evt);
            }
        });

        jbtnCerrarSesion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCerrarSesion.setText("CERRAR SESION");
        jbtnCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlMenuLayout = new javax.swing.GroupLayout(jpnlMenu);
        jpnlMenu.setLayout(jpnlMenuLayout);
        jpnlMenuLayout.setHorizontalGroup(
            jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jpnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlMenuLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jimgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlMenuLayout.createSequentialGroup()
                        .addGroup(jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtnCerrarSesion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLibroMayor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnLibroDiario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnAsientos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnEmpresas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jlblNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnEditarPerfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jpnlMenuLayout.setVerticalGroup(
            jpnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jimgUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jlblNombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnEditarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnLibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnLibroMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(jbtnCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jpnlContenedor.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnlContenedorLayout = new javax.swing.GroupLayout(jpnlContenedor);
        jpnlContenedor.setLayout(jpnlContenedorLayout);
        jpnlContenedorLayout.setHorizontalGroup(
            jpnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1051, Short.MAX_VALUE)
        );
        jpnlContenedorLayout.setVerticalGroup(
            jpnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnInicioActionPerformed
        // TODO add your handling code here:
        /*
        if (_visible == -1) {
            jButton1.setVisible(false);
            jPanel2.setVisible(false);    
            _visible = 1;
        } else {
            jPanel2.setVisible(true); 
            jButton1.setVisible(true);
            _visible = -1;
        }
        */
        MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, new Inicio());
    }//GEN-LAST:event_jbtnInicioActionPerformed

    private void jbtnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUsuariosActionPerformed
        // TODO add your handling code here:
        MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, new GestionUsuario());
    }//GEN-LAST:event_jbtnUsuariosActionPerformed

    private void jbtnEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEmpresasActionPerformed
        // TODO add your handling code here:
        GestionEmpresa frmGestionEmpresa = new GestionEmpresa();
        frmGestionEmpresa.SetFormularioPrincipal(this);
        MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, frmGestionEmpresa);
    }//GEN-LAST:event_jbtnEmpresasActionPerformed

    private void jbtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarSesionActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(
            Principal.this,
            "¿Estás seguro de que deseas cerrar la sesión?",
            "ATENCIÓN:",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE
        );

        if (response == JOptionPane.YES_OPTION) {
            _frmLogin.setVisible(true);
            this.dispose();
        }        
    }//GEN-LAST:event_jbtnCerrarSesionActionPerformed

    private void jbtnAsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAsientosActionPerformed
        // TODO add your handling code here:
        MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, new AsientoContable());
    }//GEN-LAST:event_jbtnAsientosActionPerformed

    private void jbtnLibroDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLibroDiarioActionPerformed
        // TODO add your handling code here:
        MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, new LibroDiario());
    }//GEN-LAST:event_jbtnLibroDiarioActionPerformed

    private void jbtnLibroMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLibroMayorActionPerformed
        // TODO add your handling code here:
        LibroMayor frmLibroMayor = new LibroMayor();
        frmLibroMayor.SetFormularioPrincipal(this);
        MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, frmLibroMayor);
    }//GEN-LAST:event_jbtnLibroMayorActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void SetFormularioLogin(Login frmLogin) {
        this._frmLogin = frmLogin;
    }
    
    public void SetImagLabel(JLabel lblImagen, String urlImagen) {
        ImageIcon imagen = new ImageIcon(urlImagen);
        
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(lblImagen.getWidth(), lblImagen.getHeight(), Image.SCALE_DEFAULT));
        lblImagen.setOpaque(false);
        lblImagen.setIcon(icono);
        this.repaint();
    }
    
    public void AbrirCatalogoDeEmpresas(int idEmpresa) {
        if (idEmpresa != -1) {
            CatalogoCuentas frmCatalogoCuentas = new CatalogoCuentas(idEmpresa);
            MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, frmCatalogoCuentas);
        }
    }
    
    public void AbrirCuentaT(Cuenta cuenta) {
        if (cuenta != null) {
            CuentaT cuentaT = new CuentaT(cuenta);
            MostrarPanel.Instancia().NuevoPanel(jpnlContenedor, cuentaT);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbtnAsientos;
    private javax.swing.JButton jbtnCerrarSesion;
    private javax.swing.JButton jbtnEditarPerfil;
    private javax.swing.JButton jbtnEmpresas;
    private javax.swing.JButton jbtnInicio;
    private javax.swing.JButton jbtnLibroDiario;
    private javax.swing.JButton jbtnLibroMayor;
    private javax.swing.JButton jbtnUsuarios;
    private javax.swing.JLabel jimgUsuario;
    private javax.swing.JLabel jlblNombreUsuario;
    private javax.swing.JPanel jpnlContenedor;
    private javax.swing.JPanel jpnlMenu;
    // End of variables declaration//GEN-END:variables
}
